# Numerical analysis of the 4D point-mass model: one simulation (transient ->
# pumping limit cycle) and a reproduction of the ECC2026 equilibria figure
# (test/publications/ECC2026/figs/equilibria.pdf, generated by 3_equilibria.jl
# with Makie) using Plots.jl only.

using KEEP: PointMass4 as PM4
using KEEP: PointMassPara as PMP
using KEEP: SteadyState
using KEEP: Visualization as VIZ
using KEEP.TorqueFunction: torque_function

using Plots
using LinearAlgebra: norm, eigvals

vbp = PMP.build_vbpara()

## ---------------------------------------------------------------------------
# One simulation: start near the aligned state q = (0, 0) with a prograde
# kick dq = (0, 1); the trajectory leaves the transient and settles on the
# pumping limit cycle within ~5 s (a few cycle periods).
u0 = PM4.build_u(; dτ=1)
sol = PM4.integrate(u0, 10, vbp; save_everystep=true)

N = 500
ts = range(0, sol.t[end], N)
q_ts = reduce(hcat, sol.(ts))'  # interpolated states on the grid
τm = mod.(q_ts[:, 2], 2π) .- π
@assert all(-π .<= τm .< π)
@assert all(diff(τm) .< π)  # τ is monotonically increasing through the wraps

"""
Wrapped-τ series: main polyline on the grid with a NaN sample at each 2π
crossing, plus the crossings as NaN-separated vertical segments (crossing
time twice, values π and -π) to be drawn dashed.
"""
function tau_wrap(ts, τm)
    Δt = step(ts)
    tcross = [
        ts[i] + Δt * (π - τm[i]) / (τm[i + 1] + 2π - τm[i]) for i in findall(diff(τm) .< -π)
    ]
    t_jump, y_jump = Float64[], Float64[]
    for tc in tcross
        append!(t_jump, (tc, tc, NaN))
        append!(y_jump, (π, -π, NaN))
    end
    perm = sortperm(vcat(ts, tcross))
    t_main = vcat(ts, tcross)[perm]
    y_main = vcat(τm, fill(NaN, length(tcross)))[perm]
    return t_main, y_main, t_jump, y_jump
end

"""
Same as `VIZ.plot_avg_power_4D`, but plotting in kW instead of W.
"""
function plot_avg_power_kW(sol)
    t, (t0, tf) = VIZ.build_t(extrema(sol.t), VIZ.DEFAULT_PPS)
    p = sol.prob.p
    L, M, T = PMP.lmt(p)
    dα = sol.(t; idxs=3)
    power = dα .* torque_function.(dα .* T, (p,)) .* (M * L^2 * T^-2) ./ 1000
    avg_power = sol(tf; idxs=5) / (tf - t0) / 1000
    plot(t, power; c=:black, lw=2, label="", ylabel="Power (kW)")
    plot!(
        [t0, tf],
        [avg_power, avg_power];
        c=:red,
        lw=2,
        label="Average power = $(round(avg_power; digits=2)) kW",
    )
    return plot!(;
        legend=(0.1, -0.2), xlabel="t (s)", left_margin=2Plots.mm, bottom_margin=3Plots.mm
    )
end

t_main, y_main, t_jump, y_jump = tau_wrap(ts, τm)
p_wts = plot(
    ts,
    q_ts[:, [1, 3, 4]];
    label=["α" "dα" "dτ"],
    ylabel="q (rad), qd (rad/s)",
    legend=:bottomleft,
    xlabel="",
    xformatter=x->"",
)
plot!(t_main, y_main; c=4, lw=2, label="τ mod 2π")
plot!(t_jump, y_jump; c=4, ls=:dash, label=false)
pw = plot_avg_power_kW(sol)
sim_4D_fig = plot(p_wts, pw; layout=@layout([a{0.65h}; b]), size=(800, 700))
savefig(sim_4D_fig, joinpath(@__DIR__, "figs", "simulation_4D.png"))
display(sim_4D_fig)

## ---------------------------------------------------------------------------
# Equilibria figure, Plots.jl reproduction of the Makie original.
#
# Vector field studied: ddq(q, dq = 0) = (ddα, ddτ). The 1e-100 shift avoids
# pathological points exactly on symmetry axes (as in 3_equilibria.jl).
f = q -> SteadyState.ddq_partial(q .+ 1e-100, vbp)

# Background: green when the arm points downwind (|α| < π/2), red upwind.
plot(;
    xlims=(-π - 0.2, π + 0.2),
    ylims=(-π - 0.2, π + 0.2),
    aspect_ratio=:equal,
    xticks=([-π, 0, π], ["-π", "α = 0", "π"]),
    yticks=([-π, 0, π], ["-π", "τ = 0", "π"]),
    grid=false,
    framestyle=:semi,
    legend=:outerright,
    colorbar=false,
)
vspan!([-π, -π / 2]; c=:red, alpha=0.1, label="Arm upwind")
vspan!([-π / 2, π / 2]; c=:green, alpha=0.1, label="Arm downwind")
vspan!([π / 2, π]; c=:red, alpha=0.1, label="")

"""
Port of Makie's streamplot_impl (src/basic_recipes/streamplot.jl), 2D.

A visited-cell mask covers the domain; seeds are drawn at cell centers from a
quasirandom (plastic-number) low-discrepancy sequence; from each unvisited seed
the NORMALIZED field is RK4-integrated with fixed `stepsize` forward and
backward, stopping on domain exit, on a near-zero field (equilibrium), or on
entering any visited cell (which also terminates closed loops). Repeat until
`density` of the cells are visited.
Seeding and one-arrow-per-streamline follow Makie's streamplot, which steps
explicit Euler on the unit field; the RK4 integration here is a deliberate
deviation, as Euler chatters across the attracting ddτ = 0 nullcline near
equilibria.

Returns (line_x, line_y, ax, ay, au, av): NaN-separated polyline coordinates
and seed positions / unit field directions for the arrows.
"""
function streamlines(
    f, xlims, ylims; gridsize=(20, 20), stepsize=0.1, maxsteps=10, density=1.0
)
    gx, gy = gridsize
    xmin, xmax = xlims
    ymin, ymax = ylims
    rx, ry = LinRange(xmin, xmax, gx + 1), LinRange(ymin, ymax, gy + 1)
    dx, dy = step(rx), step(ry)
    mask = trues(gx, gy)  # unvisited cells
    φ = 1.324717957244746  # plastic number
    acoeff = (φ^-1, φ^-2)
    # Unit field; nothing near an equilibrium (norm < 1e-12), which terminates
    # the integration instead of dividing 0/0.
    unit = x -> begin
        v = f(x)
        n = norm(v)
        n < 1e-12 ? nothing : (v[1] / n, v[2] / n)
    end
    # One RK4 step of size h along (or against, d = -1) the unit field.
    function step_rk4(x, d, h)
        k1 = unit(x)
        k1 === nothing && return nothing
        k2 = unit((x[1] + d * h / 2 * k1[1], x[2] + d * h / 2 * k1[2]))
        k2 === nothing && return nothing
        k3 = unit((x[1] + d * h / 2 * k2[1], x[2] + d * h / 2 * k2[2]))
        k3 === nothing && return nothing
        k4 = unit((x[1] + d * h * k3[1], x[2] + d * h * k3[2]))
        k4 === nothing && return nothing
        return (
            x[1] + d * h / 6 * (k1[1] + 2k2[1] + 2k3[1] + k4[1]),
            x[2] + d * h / 6 * (k1[2] + 2k2[2] + 2k3[2] + k4[2]),
        )
    end
    line_x, line_y = Float32[], Float32[]
    ax, ay, au, av = Float32[], Float32[], Float32[], Float32[]
    visited = 0
    ind = 0
    while visited < gx * gy * min(1.0, density)
        cind = ind
        ind += 1
        ci = clamp(ceil(Int, ((0.5 + acoeff[1] * cind) % 1) * gx), 1, gx)
        cj = clamp(ceil(Int, ((0.5 + acoeff[2] * cind) % 1) * gy), 1, gy)
        mask[ci, cj] || continue
        x0 = (xmin + (ci - 0.5) * dx, ymin + (cj - 0.5) * dy)
        v0 = f(x0)
        n0 = norm(v0)
        push!(ax, x0[1])
        push!(ay, x0[2])
        push!(au, v0[1] / n0)
        push!(av, v0[2] / n0)
        mask[ci, cj] = false
        visited += 1
        for d in (-1, 1)
            x = x0
            ccur = (ci, cj)
            push!(line_x, NaN)
            push!(line_y, NaN)
            push!(line_x, x[1])
            push!(line_y, x[2])
            npts = 1
            while xmin ≤ x[1] ≤ xmax && ymin ≤ x[2] ≤ ymax && npts < maxsteps
                x = step_rk4(x, d, stepsize)
                x === nothing && break
                (xmin ≤ x[1] ≤ xmax && ymin ≤ x[2] ≤ ymax) || break
                idx = (
                    clamp(searchsortedlast(rx, x[1]), 1, gx),
                    clamp(searchsortedlast(ry, x[2]), 1, gy),
                )
                if idx != ccur
                    mask[idx...] || break
                    mask[idx...] = false
                    visited += 1
                    ccur = idx
                end
                push!(line_x, x[1])
                push!(line_y, x[2])
                npts += 1
            end
        end
    end
    return (line_x, line_y, ax, ay, au, av)
end

line_x, line_y, ax, ay, au, av = streamlines(f, (-π, π), (-π, π))
plot!(line_x, line_y; c=:grey, alpha=0.5, lw=0.5, label="")

# Arrowhead at each streamline seed (Makie-style). GR's quiver always draws
# shaft + fixed-size head (gr_polyline + GR.drawarrow), so marker-only heads
# are rendered as triangles, one series for all seeds.
L, W = 0.045, 0.016  # head length / half-width, data units
heads = [
    Shape([
        (s[1] + L / 2 * u, s[2] + L / 2 * v),          # tip
        (s[1] - L / 2 * u - W * v, s[2] - L / 2 * v + W * u),
        (s[1] - L / 2 * u + W * v, s[2] - L / 2 * v - W * u),
    ]) for (s, u, v) in zip(zip(ax, ay), au, av)
]
plot!(heads; c=:grey, alpha=0.6, label="")

# Nullclines ddτ = 0 (green) and ddα = 0 (magenta); matrices are built with
# rows = τ, cols = α to match Plots' contour orientation (rows = y).
N = 20
αs = range(-π, π, N + 1)
τs = range(-π, π, 2N + 1)
dd = [f((α, τ)) for τ in τs, α in αs]
contour!(αs, τs, last.(dd); levels=[0], c=:green, lw=2)
contour!(αs, τs, first.(dd); levels=[0], c=:magenta, lw=2)
# Contour legend entries are unreliable on GR; add them explicitly.
plot!([NaN], [NaN]; c=:green, label="ddτ = 0")
plot!([NaN], [NaN]; c=:magenta, label="ddα = 0")

# Equilibria at the nullcline intersections.
ss = SteadyState.all_steady_states(vbp)
scatter!(first.(ss), last.(ss); c=:black, ms=5, label="Equilibrium")

savefig(joinpath(@__DIR__, "figs", "equilibria.png"))
savefig(joinpath(@__DIR__, "figs", "equilibria.pdf"))
display(current())
@error "Chance to use Poincaré-Miranda theorem?"

# Sanity: the nullclines pass through the equilibria (|ddq| ≈ 0 there).
@assert maximum(norm(f(q)) for q in ss) < 1e-6
@assert 0 < last(sol.u)[5] / last(sol.t)  # positive average power over the simulation

## Limit Cycles
# TODO
# - two limit cycles
# - convergence rate plot with trend line before numerical noise takes over + visualize all floquet exponents, or multipliers (which is more relevant?)
# - 3d plot projected on zy plane
# - eight circle plot of equilibria and one limit cycle
# inspired from test/publications/ECC2026
