## Singularité

using StaticArrays
using KEEP.PointMassPara
import KEEP.PointMass4 as PM4
using LinearAlgebra

function dynamics_(u, p::Para, t)
    begin
        α, _ = q = u[1:2]
        dα, _ = dq = u[3:4]

        # Compute values and derivatives
        Rτ, D_Rτ, DD_Rτ = PM4.val_deriv_scnd_deriv(q_ -> PM4.compute_Rτ(q_, p), q, p.diffbackend)
        OK, D_OK, DD_OK = PM4.val_deriv_scnd_deriv(Rτ_ -> PM4.compute_OK(Rτ_, p), Rτ, p.diffbackend)

        # Compute unit vectors
        αhat = PM4.compute_αhat(α)
        OA = p.l * αhat
        rhat = normalize(OK - OA)

        # Compute gravity force
        linear_density_l = π * p.ρ_l * (p.d_l^2) / 4
        m_l = p.nb_l * linear_density_l * p.r/2
        Fgrav = SA[0, 0, -p.g * (p.m + m_l)]

        # Compute aerodynamical force
        wind = SA[p.v_ref * abs(OK[3] / p.h_ref)^p.n_wind, 0, 0]
        kite_speed = D_OK * D_Rτ * dq
        app_wind = wind - kite_speed  # apparent wind, We

        # Wind projected in the plane generated by (θ_hat, φ_hat)
        app_wind_perp_to_lines = app_wind - (rhat ⋅ app_wind) * rhat
        ew = normalize(app_wind_perp_to_lines)
        
        xw = -normalize(app_wind)
        yw = rhat × ew
        zw = xw × yw

        lift_k = 1//2 * p.S * p.ρ_air * norm(app_wind)^2 * p.C_L
        drag_k = lift_k * p.C_D / p.C_L
        drag_l = 1//6 * p.nb_l * p.ρ_air * p.d_l * p.C_D_l * p.r * norm(app_wind_perp_to_lines)^2
        Faero_on_kite = -drag_k * xw - lift_k * zw
        Faero_on_lines = drag_l .* ew
        Faero = Faero_on_kite + Faero_on_lines
    end
	# torque with same sign as dα, the torque applied by the arm on the generator
	torque = p.torque_func(dα, p)
	l_tension = rhat ⋅ (SA[0, 0, 1] × OA)
	A_tension = -p.I_eq / l_tension * rhat * SA[1, 0]'
	b_tension = -torque / l_tension * rhat
	
	A = p.m * D_OK * D_Rτ - A_tension
	b = (
		p.m * PM4.eval_scnd_deriv(DD_OK, D_Rτ * dq) +
		p.m * D_OK * PM4.eval_scnd_deriv(DD_Rτ, dq) +
		-b_tension - Fgrav - Faero
	)
    @show(D_OK' * A)
    @show(-D_OK' * b)
	instantaneous_power = torque * dα
	ddq = (D_OK' * A) \ (-D_OK' * b)
	return SA[dq..., ddq..., instantaneous_power]
end
#=
analyse de la singularité :
D_OK, D_Rτ OK
A KO
  - p.m * D_OK * D_Rτ OK
  - A_tension KO

=#

begin
    p = build_para()
    u1 = SA[0.0, 1e-1, 0.0, 0.0, 0.0]
    u2 = SA[0.0, 1e-10, 0.0, 0.0, 0.0]
    u3 = SA[0.0, eps(Float64)/2.68850100739755, 0.0, 0.0, 0.0]
    u4 = SA[0.0, π, 0.0, 0.0, 0.0]
    # u = zero(y1)
    # dynamics_(u1, p, 0);
    # dynamics_(u2, p, 0);
    dynamics_(u3, p, 0);
    # dynamics_(u4, p, 0);
    # dynamics_(u, p, 0);
end;



